
# -*- mode: python ; coding: utf-8 -*-
# this is all auto generated by pyinstaller

a = Analysis(
    ['virus.py'],
    pathex=[],
    binaries=[],
    datas=[('virus.mp4', '.'), ('yolov8s.pt', '.')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='virus',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
app = BUNDLE(
    exe,
    name='virus.app',
    icon=None,
    bundle_identifier=None,
)
